blank_issues_enabled: false
contact_links:
  - name: Turbopack in Next.js Bug Report
    url: https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml
    about: Create a Next.js bug report for the Turbopack team
  - name: Ask a question
    url: https://github.com/vercel/turbo/discussions
    about: Ask questions and discuss ideas with other community members
